[package]
name = "parlor-room"
version = "0.1.0"
edition = "2024"

[dependencies]
amqprs = "2"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
mockall = "0.13"
tokio-test = "0.1"
